package com.example.fitquest

import java.util.Date

data class UserProfile(
    val id: String? = null,
    val username: String = "",
    val fullName: String = "",
    val profileImage: Int = R.drawable.default_profile_image,
    val gender: String = "",
    val age: Int = 0,
    val weight: Double = 0.0,
    val height: Double = 0.0,
    val goal: String = "",
    val motivation: String = "",
    val pushUps: String = "",
    val activityLevel: String = "",
    val firstDayOfWeek: String = "",
    val trainingDays: String = "",
    val sessionsOutside: String = "",
    var xp_total: Int = 0,
    val xp_level: Int = 0,
    val level: Int = 0,
    val joinDate: String = "",
    val longestStreak: Int = 0,
    var places: List<PlaceData> = emptyList(),
    val friends: List<UserProfile> = emptyList(),
    val friend_reqs: List<UserProfile> = emptyList(),
    val achievements: List<Achievement> = emptyList(),
    val progress: Int = 0,
    val uniqueCode: String = "",
    val lastLoginDate: Date? = Date(),
    val currentStreak: Int = 0,
    var profileImageUrl: String? = null,
    var steps: Int = 0,
)
